### PR TITLE
Add paper annotation

### PR DESCRIPTION
**Pull request by bzrudski**
I have started adding annotations to my list of assigned papers. I think that it could be a good exercise for us to do the annotation on a separate branch and then merge the labelled data into the `main` branch. Tentative columns added to the `selected_papers.csv` file (in this case, `selected_papers_benjamin.csv` (subject to change due to #5):
* Data available
* Open access
* Notes

Perhaps we should also add in a **Code available** column, depending again on what we decide in Issue #5. Feel free to add other commits to this branch related to annotation.

### CODE REVIEW

**Comment by aosakwe** [comment]
Thanks for this @bzrudski ! I think a Code available column would be good to add. I also agree with doing this on a separate branch, it's a good idea. Should we wait for everyone to add their annotations to merge?

**Comment by bzrudski** [comment]
Thanks @aosakwe for the suggestions!

> I think a Code available column would be good to add.

Sounds good! I think we should mark it as `TRUE`, `FALSE` or `N/A` (since not all of them have code). I'll work on adding to mine. Also, should we stick to the first 10 papers, or can we do more if we have time?

> Should we wait for everyone to add their annotations to merge?

Yes, I think so. Anyone can commit and push to the branch and it'll automatically be added to the PR.

**Comment by aosakwe** [comment]
@bzrudski  If people have time to do more I think that's fair game. @tugcegurbuz  wrote up a script to scrape the text from all the doi links and I will work with her to see how to use it to best identify data/code availability in all the publications. The more papers we have that were manually curated, the easier it will be for us to determine how well the script categorizes the papers.

**Comment by bzrudski** [comment]
@michellewang, for taking out a review, did you delete the line or mark it somehow? I have a review and a meta-analysis in my list that I need to take out.

**Comment by bzrudski** [comment]
Also, in case anyone needs needs the column names to add to the files:
"Data Available" "Open Access" "Code Available" "Notes"

The first three columns are all `TRUE`/`FALSE`.

**Comment by michellewang** [comment]
@bzrudski I just deleted the line, to stay consistent with the columns. But I was just looking over everyone's files and I noticed that Jack added a "Review" column.

**Comment by bzrudski** [comment]
> @bzrudski I just deleted the line, to stay consistent with the columns. But I was just looking over everyone's files and I noticed that Jack added a "Review" column.

Thanks! I'll keep track of which ones I remove. Maybe I'll move the line to a different file.

**Pull request merged**
